"""Booking a activated

Revision ID: 55b132d1291c
Revises: fa96f140e579
Create Date: 2018-06-11 08:21:25.925206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b132d1291c'
down_revision = 'fa96f140e579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('activated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'activated')
    # ### end Alembic commands ###
