"""email_confirmed field

Revision ID: fa96f140e579
Revises: 8116d233bbb1
Create Date: 2018-06-11 06:20:45.392890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa96f140e579'
down_revision = '8116d233bbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'email_confirmed')
    # ### end Alembic commands ###
